### ISSUE TITLE
failure in query 

### ISSUE THREAD

**Issue by adrianhsm** [leptonai/search_with_lepton#44]
2024-02-03 14:15:48.540 | INFO     | __main__:query_function:570 - Key 4lzfpPBR_pabKHefwv6zf not found, will generate again.
2024-02-03 14:15:50.437 | ERROR    | __main__:query_function:620 - encountered error: module 'openai' has no attribute 'OpenAI'
Traceback (most recent call last):
  File "/Users/smai/workspace/ai/search_with_lepton/search_with_lepton.py", line 365, in local_client
    return thread_local.client
           ^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/smai/workspace/ai/search_with_lepton/search_with_lepton.py", line 599, in query_function
    client = self.local_client()
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/smai/workspace/ai/search_with_lepton/search_with_lepton.py", line 367, in local_client
    thread_local.client = openai.OpenAI(
                          ^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'OpenAI'

2024-02-03 14:15:50,438 - INFO:     127.0.0.1:64223 - "POST /query HTTP/1.1" 200 OK

**Comment by adrianhsm** [comment]
Following readme.md seems not able to fix all the problem, could anyone improve the deployment doc?

**Comment by jcdiv47** [comment]
I think a reasonable debug starting point could be checking the version of `openai` package on your end, make sure it is up-to-date with command

```
pip install -U openai
```
