### ISSUE TITLE
Why >lep login Failed？？？

### ISSUE THREAD

**Issue by New-King** [leptonai/search_with_lepton#84]
root@iZt4n5462zgbdxz4pnhy3iZ:/home/search_with_lepton# lep login
========================================================
    _     _____ ____ _____ ___  _   _       _    ___     
   | |   | ____|  _ \_   _/ _ \| \ | |     / \  |_ _|    
   | |   |  _| | |_) || || | | |  \| |    / _ \  | |     
   | |___| |___|  __/ | || |_| | |\  |   / ___ \ | |     
   |_____|_____|_|    |_| \___/|_| \_|  /_/   \_\___|    

========================================================
Traceback (most recent call last):
  File "/usr/local/bin/lep", line 8, in <module>
    sys.exit(lep())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/leptonai/cli/cli.py", line 146, in login
    info = api_client.info()
  File "/usr/local/lib/python3.10/dist-packages/leptonai/api/v1/client.py", line 177, in info
    response = self._get("/workspace")
  File "/usr/local/lib/python3.10/dist-packages/leptonai/api/v1/client.py", line 155, in _get
    return self._session.get(self.url + path, *args, **self._safe_add(kwargs))
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/api/v1/workspace': No scheme supplied. Perhaps you meant https:///api/v1/workspace?

**Comment by New-King** [comment]
This error will be reported when I type the command BACKEND=BING python3 search_with_lepton.py or lep login

**Comment by bruceguo123** [comment]
Did the problem get resolved? I am facing the same issue.

**Comment by bruceguo123** [comment]
How did you solve the problem? Please share your method, as I am facing the same issue.
