### ISSUE TITLE
Why >lep login Failed？？？

### ISSUE THREAD

**Issue by New-King** [leptonai/search_with_lepton#85]
root@iZt4n5462zgbdxz4pnhy3iZ:/home/search_with_lepton# lep login

========================================================
Traceback (most recent call last):
File "/usr/local/bin/lep", line 8, in
sys.exit(lep())
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/leptonai/cli/cli.py", line 146, in login
info = api_client.info()
File "/usr/local/lib/python3.10/dist-packages/leptonai/api/v1/client.py", line 177, in info
response = self._get("/workspace")
File "/usr/local/lib/python3.10/dist-packages/leptonai/api/v1/client.py", line 155, in _get
return self._session.get(self.url + path, *args, **self._safe_add(kwargs))
File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 575, in request
prep = self.prepare_request(req)
File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 486, in prepare_request
p.prepare(
File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 368, in prepare
self.prepare_url(url, params)
File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 439, in prepare_url
raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/api/v1/workspace': No scheme supplied. Perhaps you meant https:///api/v1/workspace?

**Comment by New-King** [comment]
This error will be reported when I type the command BACKEND=SERPER python3 search_with_lepton.py or lep log

**Comment by New-King** [comment]
![image](https://github.com/leptonai/search_with_lepton/assets/16871008/f8f0012d-5591-4bf3-bc7c-2e62d8e06673)

It will be fine when I comment on this code, but wonder what the impact will be?

**Comment by New-King** [comment]
god i need a code god！ help me please！

**Comment by xlu451** [comment]
Thank you for submitting the issue. Here are some steps to resolve it:

1. Register an account and open your workspace at [lepton.ai](https://www.lepton.ai/).
2. Ensure you are using the latest version of the `leptonai` package by running:
   ```bash
   pip install --upgrade leptonai
   ```
3. List your workspaces with:
   ```bash
   lep workspace list
   ```
4. Remove the local workspace with the error:
   ```bash
   lep workspace remove -i <your-local-workspace-id-with-this-error>
   ```
5. Log in again:
   ```bash
   lep login
   ```
   Copy the credentials and paste the credentials in command prompt

   If you already know your credentials (which you can find in your workspace settings under tokens), you can also use:
   ```bash
   lep login -c your_workspace_id:your_token
   ```

If the issue persists, please reach out for assistance.

**Comment by bruceguo123** [comment]
this problem has been resolved, see here:https://github.com/leptonai/leptonai/issues/432
