### ISSUE TITLE
when I use npm run build, it throws the error that useSearchParams() should be wrapped in a suspense boundary at page "/search"

### ISSUE THREAD

**Issue by comi-zhang** [leptonai/search_with_lepton#98]
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (2/7)  [==  ] ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/search". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at o (C:\Users\Fine\SearchEngine\search_with_lepton\web\.next\server\chunks\349.js:1:10784)
    at s (C:\Users\Fine\SearchEngine\search_with_lepton\web\.next\server\chunks\349.js:1:21720)
    at lm (C:\Users\Fine\SearchEngine\search_with_lepton\web\.next\server\app\search\page.js:1:219862)
    at nj (C:\Users\Fine\SearchEngine\search_with_lepton\web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:46251)
    at nM (C:\Users\Fine\SearchEngine\search_with_lepton\web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47571)
    at nN (C:\Users\Fine\SearchEngine\search_with_lepton\web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64546)
    at nI (C:\Users\Fine\SearchEngine\search_with_lepton\web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47010)
    at nM (C:\Users\Fine\SearchEngine\search_with_lepton\web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47717)
    at nM (C:\Users\Fine\SearchEngine\search_with_lepton\web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:61546)
    at nN (C:\Users\Fine\SearchEngine\search_with_lepton\web\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64546)

Error occurred prerendering page "/search". Read more: https://nextjs.org/docs/messages/prerender-error

 ✓ Generating static pages (7/7)

> Export encountered errors on following paths:
        /search/page: /search

**Comment by qianghuang84** [comment]
find the solution from https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout

**Comment by CalvinJamesHeath** [comment]
Same issue here. 
Solution for Docker: 
```
RUN npm ci \
 && node -e "const fs=require('fs');const p='next.config.mjs';let s=fs.readFileSync(p,'utf8');if(!/missingSuspenseWithCSRBailout/.test(s)){if(/export\\s+default\\s+/.test(s)){s=s.replace(/export\\s+default\\s+/,'const __CFG__ = ');s+='\\nexport default { ...__CFG__, experimental: { ...( __CFG__.experimental || {}), missingSuspenseWithCSRBailout: false } };\\n';}else{s+='\\nexport default { experimental: { missingSuspenseWithCSRBailout: false } };\\n';}fs.writeFileSync(p,s);}" \
 && npx --yes next@14.2.22 build \
 && npm cache clean --force \
 && rm -rf ~/.npm
```
